# Generated by Django 4.2.9 on 2024-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_paciente', models.CharField(max_length=120)),
                ('procedimento', models.CharField(max_length=120)),
                ('sexo', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Feminino'), ('NI', 'Prefere não Informar')], default='NI', max_length=2)),
                ('idade', models.IntegerField()),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('data_cad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
